################################################################################################################################################################

# @project        Library/IO
# @file           tools/python/docker/Dockerfile
# @author         Lucas Brémond <lucas@loftorbital.com>
# @license        TBD

################################################################################################################################################################

FROM jupyter/scipy-notebook:latest

LABEL maintainer="lucas@loftorbital.com"

USER root

RUN ln -s /opt/conda/include/python3.6m /opt/conda/include/python3.6

RUN cd /tmp \
 && wget --quiet http://sourceforge.net/projects/boost/files/boost/1.68.0/boost_1_68_0.tar.gz \
 && tar -xf boost_1_68_0.tar.gz \
 && cd boost_1_68_0 \
 && ./bootstrap.sh --with-python=/opt/conda/bin/python3 --with-python-version=3.6 --with-python-root=/opt/conda/lib/python3.6 \
 && echo "using python : 3.6 : /usr : /opt/conda/include/python3.6m ;" >> project-config.jam \
 && ./b2 --with-python -j 8 install \
 && rm -rf /tmp/boost_1_68_0

RUN jupyter labextension install @jupyterlab/plotly-extension

COPY ./shortcuts-extension /home/jovyan/.jupyter/lab/user-settings/@jupyterlab/shortcuts-extension

RUN chown -R $NB_UID:$NB_UID /home/jovyan/.jupyter

RUN apt-get update -y


####

# Environment

ENV cpu_count 8
ENV LD_LIBRARY_PATH /usr/local/lib:${LD_LIBRARY_PATH}
ENV PYTHONPATH /usr/local/lib:${PYTHONPATH}

# Development Tools

## Compilers

RUN apt-get install -y cmake python3-devel python3-numpy

## Python Tools

RUN python3 -m pip install --user --upgrade setuptools wheel twine

## CMake [3.12.2]

RUN pushd /tmp > /dev/null \
 && wget --quiet https://cmake.org/files/v3.12/cmake-3.12.2.tar.gz \
 && tar -xf cmake-3.12.2.tar.gz \
 && cd cmake-3.12.2 \
 && ./bootstrap \
 && make -j ${cpu_count} \
 && make install \
 && popd > /dev/null \
 && rm -rf /tmp/cmake-3.12.2 /tmp/cmake-3.12.2.tar.gz

## GoogleTest [1.8.1]

RUN pushd /tmp > /dev/null \
 && git clone --branch release-1.8.1 --depth 1 https://github.com/google/googletest.git \
 && cd googletest \
 && mkdir build \
 && cd build \
 && cmake .. \
 && make -j ${cpu_count} \
 && make install \
 && popd > /dev/null \
 && rm -rf /tmp/googletest

## Boost [1.68.0]

RUN pushd /tmp > /dev/null \
 && wget --quiet http://sourceforge.net/projects/boost/files/boost/1.68.0/boost_1_68_0.tar.gz \
 && tar -xf boost_1_68_0.tar.gz \
 && cd boost_1_68_0 \
 && ./bootstrap.sh --with-python=/usr/bin/python3 --with-python-version=3.6 --with-python-root=/usr/lib/python3.6 \
 && echo "using python : 3.6 : /usr : /usr/include/python3.6m ;" >> project-config.jam \
 && ./b2 -j ${cpu_count} link=static cxxflags=-fPIC install \
 && ./b2 -j ${cpu_count} --with-python link=shared cxxflags=-fPIC install \
 && popd > /dev/null \
 && rm -rf /tmp/boost_1_68_0 /tmp/boost_1_68_0.tar.gz

## RapidJSON [1.1.0]

RUN pushd /tmp > /dev/null \
 && git clone https://github.com/miloyip/rapidjson.git \
 && cd rapidjson \
 && mkdir build \
 && cd build \
 && cmake .. \
 && make --silent -j ${cpu_count} \
 && make install \
 && rm -rf /tmp/rapidjson \
 && popd > /dev/null

## ordered-map [0.6.0]

RUN pushd /tmp > /dev/null \
 && git clone --branch v0.6.0 --depth 1 https://github.com/Tessil/ordered-map.git \
 && cd ordered-map \
 && cp -r ./include/tsl /usr/local/include \
 && rm -rf /tmp/ordered-map \
 && popd > /dev/null

## {fmt} [5.2.0]

RUN pushd /tmp > /dev/null \
 && git clone --branch 5.2.0 --depth 1 https://github.com/fmtlib/fmt.git \
 && cd fmt \
 && mkdir build \
 && cd build \
 && cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE .. \
 && make --silent -j ${cpu_count} \
 && make install \
 && rm -rf /tmp/fmt \
 && popd > /dev/null

## Rapidcsv [master]

RUN pushd /tmp > /dev/null \
 && git clone https://github.com/d99kris/rapidcsv.git \
 && cd rapidcsv \
 && mkdir -p /usr/local/include/rapidcsv \
 && cp src/*.h /usr/local/include/rapidcsv/ \
 && rm -rf /tmp/rapidcsv \
 && popd > /dev/null

RUN pushd /tmp > /dev/null \
 && git clone --branch 0.13-release --depth 1 https://github.com/cpp-netlib/cpp-netlib \
 && cd cpp-netlib \
 && git submodule init \
 && git submodule update \
 && mkdir build \
 && cd build \
 && cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON .. \
 && make -j ${cpu_count} \
 && make install \
 && popd > /dev/null \
 && rm -rf /tmp/cppnetlib

## Library ▸ Core [0.1.19]

# RUN mkdir -p /tmp/library-core \
#  && pushd /tmp/library-core > /dev/null \
#  && wget --quiet https://github.com/open-space-collective/library-core/releases/download/0.1.19/library-core-0.1.19-1.x86_64-runtime.rpm \
#  && wget --quiet https://github.com/open-space-collective/library-core/releases/download/0.1.19/library-core-0.1.19-1.x86_64-devel.rpm \
#  && dnf install -y ./*.rpm \
#  && rm -rf /tmp/library-core \
#  && popd > /dev/null

################################################################################################################################################################